version: "3"
services:
  meteor:
    build: .
    ports:
      - 8080:8080
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/jwpublic
      - ROOT_URL=http://localhost:8080
    restart: always
  mongo:
    image: mongo:3.7
    volumes:
      - "./database:/data/db:rw"
    restart: always
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 9090:8081
  #   links:
  #     - mongo
