apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jw-public/trolleyapp:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jw-public/trolleyapp:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: trolleyapp
        chartPath: charts/trolleyapp
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jw-public/trolleyapp"
          image.tag: "{{.TAG}}"
