apiVersion: apps/v1
kind: Deployment
metadata:
  name: jw-public
spec:
  template:
    spec:
      containers:
        - name: jw-public
          env:
            - name: ROOT_URL
              value: https://jw-public.org
            - name: MAIL_URL
              value: smtp://ses-relay.ses-relay.svc.cluster.local:25
            - name: VIRTUAL_HOST
              value: jw-public.org
