name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
    pull_request:
      - "*"

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: jw-public

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v2
        with:
          path: src/.meteor/local
          key: ${{ runner.os }}-node-${{ hashFiles('src/.meteor/versions') }}
          restore-keys: |
            ${{ runner.os }}-meteor-
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: "1.12"
      - run: cd src && meteor npm install
      - run: cd src && meteor npm run compile
      - run: cd src && meteor npm test
      - run: cd src && meteor build --allow-superuser --architecture=os.linux.x86_64 ./build
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: "1.12"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v2
        with:
          path: src/.meteor/local
          key: ${{ runner.os }}-node-${{ hashFiles('src/.meteor/versions') }}
          restore-keys: |
            ${{ runner.os }}-meteor-
      - run: cd src && meteor npm install
      - run: cd src && meteor npm run compile
      - run: cd src && meteor npm test
      - run: cd src && meteor build --allow-superuser --architecture=os.linux.x86_64 ./build
      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
